import { Company, Transaction, Payment, Return, Expense, Notification, User, Product } from './types';

export const dummyCompanies: Company[] = [
  {
    id: 'c1',
    name: 'Acme Corp',
    type: 'customer',
    paymentTermsDays: 30,
    email: 'contact@acmecorp.com',
    phone: '+1-555-0101',
    ageingBrackets: { bracket1: 30, bracket2: 60, bracket3: 90 },
  },
  {
    id: 'c2',
    name: 'Global Supply Ltd',
    type: 'supplier',
    paymentTermsDays: 45,
    email: 'orders@globalsupply.com',
    phone: '+1-555-0102',
    ageingBrackets: { bracket1: 30, bracket2: 60, bracket3: 90 },
  },
  {
    id: 'c3',
    name: 'Tech Solutions Inc',
    type: 'customer',
    paymentTermsDays: 30,
    email: 'sales@techsolutions.com',
    phone: '+1-555-0103',
    ageingBrackets: { bracket1: 30, bracket2: 60, bracket3: 90 },
  },
  {
    id: 'c4',
    name: 'Premium Materials Co',
    type: 'supplier',
    paymentTermsDays: 60,
    email: 'procurement@premiummat.com',
    phone: '+1-555-0104',
    ageingBrackets: { bracket1: 30, bracket2: 60, bracket3: 90 },
  },
  {
    id: 'c5',
    name: 'Enterprise Systems Ltd',
    type: 'customer',
    paymentTermsDays: 45,
    email: 'billing@enterprise.com',
    phone: '+1-555-0105',
    ageingBrackets: { bracket1: 30, bracket2: 60, bracket3: 90 },
  },
];

export const dummyTransactions: Transaction[] = [
  {
    id: 't1',
    type: 'sale',
    companyId: 'c1',
    amount: 50000,
    date: '2024-03-01',
    invoiceNumber: 'INV-001',
    description: 'Software license sales',
    status: 'paid',
  },
  {
    id: 't2',
    type: 'sale',
    companyId: 'c3',
    amount: 75000,
    date: '2024-03-05',
    invoiceNumber: 'INV-002',
    description: 'Consulting services',
    status: 'pending',
  },
  {
    id: 't3',
    type: 'purchase',
    companyId: 'c2',
    amount: 120000,
    date: '2024-02-28',
    invoiceNumber: 'PO-001',
    description: 'Equipment purchase',
    status: 'partial',
  },
  {
    id: 't4',
    type: 'sale',
    companyId: 'c5',
    amount: 95000,
    date: '2024-03-10',
    invoiceNumber: 'INV-003',
    description: 'System implementation',
    status: 'pending',
  },
  {
    id: 't5',
    type: 'purchase',
    companyId: 'c4',
    amount: 45000,
    date: '2024-03-02',
    invoiceNumber: 'PO-002',
    description: 'Raw materials',
    status: 'paid',
  },
  {
    id: 't6',
    type: 'sale',
    companyId: 'c1',
    amount: 35000,
    date: '2024-03-12',
    invoiceNumber: 'INV-004',
    description: 'Maintenance contract',
    status: 'pending',
  },
];

export const dummyPayments: Payment[] = [
  {
    id: 'p1',
    transactionId: 't1',
    amount: 50000,
    date: '2024-03-20',
    status: 'completed',
  },
  {
    id: 'p2',
    transactionId: 't3',
    amount: 60000,
    date: '2024-03-15',
    status: 'completed',
  },
  {
    id: 'p3',
    transactionId: 't5',
    amount: 45000,
    date: '2024-03-10',
    status: 'completed',
  },
];

export const dummyReturns: Return[] = [
  {
    id: 'r1',
    transactionId: 't2',
    type: 'sale',
    companyId: 'c3',
    amount: 10000,
    date: '2024-03-18',
    reason: 'Product defect',
    invoiceNumber: 'RET-001',
    status: 'approved',
  },
  {
    id: 'r2',
    transactionId: 't4',
    type: 'sale',
    companyId: 'c5',
    amount: 5000,
    date: '2024-03-20',
    reason: 'Partial return',
    invoiceNumber: 'RET-002',
    status: 'pending',
  },
];

export const dummyExpenses: Expense[] = [
  {
    id: 'e1',
    category: 'courier',
    amount: 2500,
    date: '2024-03-15',
    description: 'Delivery charges - March shipments',
    status: 'approved',
  },
  {
    id: 'e2',
    category: 'travel',
    amount: 8000,
    date: '2024-03-10',
    description: 'Client meeting - City Center',
    status: 'approved',
  },
  {
    id: 'e3',
    category: 'food',
    amount: 1500,
    date: '2024-03-18',
    description: 'Team lunch meeting',
    status: 'pending',
  },
  {
    id: 'e4',
    category: 'other',
    amount: 5000,
    date: '2024-03-12',
    description: 'Office supplies',
    status: 'approved',
  },
];

export const dummyNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'payment_due',
    transactionId: 't2',
    companyId: 'c3',
    message: 'Payment due for INV-002 (Tech Solutions Inc)',
    severity: 'warning',
    date: '2024-04-04',
    read: false,
    actionUrl: '/payments',
  },
  {
    id: 'n2',
    type: 'payment_overdue',
    transactionId: 't4',
    companyId: 'c5',
    message: 'Payment overdue for INV-003 (Enterprise Systems Ltd) - 5 days',
    severity: 'error',
    date: '2024-03-24',
    read: false,
    actionUrl: '/payments',
  },
  {
    id: 'n3',
    type: 'return_pending',
    transactionId: 't4',
    companyId: 'c5',
    message: 'Return RET-002 pending approval',
    severity: 'info',
    date: '2024-03-20',
    read: false,
    actionUrl: '/returns',
  },
  {
    id: 'n4',
    type: 'expense_pending',
    companyId: 'c1',
    message: 'Expense approval needed - Team lunch meeting',
    severity: 'warning',
    date: '2024-03-18',
    read: false,
    actionUrl: '/expenses',
  },
];

export const dummyProducts: Product[] = [
  {
    id: 'prd1',
    code: 'PRD-001',
    name: 'Industrial Valve A1',
    description: 'High-pressure industrial valve for steam systems.',
    price: 4500,
    stock: 25,
    category: 'Hardware',
  },
  {
    id: 'prd2',
    code: 'PRD-002',
    name: 'Steel Pipe 2-inch',
    description: 'Stainless steel pipe, 2-inch diameter, 6m length.',
    price: 1200,
    stock: 150,
    category: 'Raw Materials',
  },
  {
    id: 'prd3',
    code: 'PRD-003',
    name: 'Hydraulic Pump HP-50',
    description: 'Heavy duty hydraulic pump for industrial machinery.',
    price: 12500,
    stock: 8,
    category: 'Machinery',
  },
];

export const dummyUser: User = {
  id: 'u1',
  username: 'admin',
  password: 'admin123',
  name: 'Admin User',
  role: 'admin',
  accessibleModules: ['/sales', '/purchases', '/returns', '/expenses', '/companies', '/payments', '/inventory', '/notifications', '/settings'],
};

export const dummyCredentials = {
  username: 'admin',
  password: 'admin123',
};
