import { Company, Transaction, Payment, Return, Expense, Notification, User, Product } from './types';

export const dummyCompanies: Company[] = [
  {
    id: 'c1',
    name: 'Precision Engineering Shoppe',
    type: 'supplier',
    contactPerson: 'Arvind Mehra',
    contactPersonPhone: '+91 98200 11111',
    phone: '+91 98200 12345',
    email: 'sales@precision-eng.com',
    address: 'G-12, Industrial Estate, Phase 3, Andheri West',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400053',
    gstin: '27AABCP1234A1Z1',
    pan: 'AABCP1234A',
    paymentTermsDays: 45,
    status: 'active',
  },
  {
    id: 'c2',
    name: 'Bharat Heavy Electricals Ltd',
    type: 'customer',
    contactPerson: 'S. K. Verma',
    contactPersonPhone: '+91 11 2345 0000',
    phone: '+91 11 2345 6789',
    email: 'procurement@bhel.co.in',
    address: 'BHEL House, Siri Fort',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110049',
    gstin: '07AAACB1234C1Z2',
    pan: 'AAACB1234C',
    paymentTermsDays: 60,
    creditLimit: 5000000,
    status: 'active',
  },
  {
    id: 'c3',
    name: 'Shivam Steel Traders',
    type: 'supplier',
    contactPerson: 'Jignesh Shah',
    contactPersonPhone: '+91 79 2658 1111',
    phone: '+91 79 2658 0000',
    email: 'shivam.steel@gmail.com',
    address: 'Plot No. 45, GIDC Industrial Estate',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '382445',
    gstin: '24AHGPS1234P1Z3',
    pan: 'AHGPS1234P',
    paymentTermsDays: 30,
    status: 'active',
  },
  {
    id: 'c4',
    name: 'MMRDA - Metro Line 3',
    type: 'customer',
    contactPerson: 'Nitin Gadkari',
    contactPersonPhone: '+91 22 2659 2222',
    phone: '+91 22 2659 0001',
    email: 'info@mmrda.maharashtra.gov.in',
    address: 'Bandra-Kurla Complex, Bandra (E)',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400051',
    gstin: '27AAAMM1234M1Z4',
    pan: 'AAAMM1234M',
    paymentTermsDays: 90,
    creditLimit: 10000000,
    status: 'active',
  },
  {
    id: 'c5',
    name: 'Apex Infrastructure Solutions',
    type: 'customer',
    contactPerson: 'Rahul Iyer',
    contactPersonPhone: '+91 80 4123 3333',
    phone: '+91 80 4123 4567',
    email: 'projects@apex-infra.com',
    address: '14, RMV 2nd Stage, Lottegollahalli',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560094',
    gstin: '29AAACA1234A1Z5',
    pan: 'AAACA1234A',
    paymentTermsDays: 30,
    creditLimit: 2500000,
    status: 'active',
  },
];

export const dummyProducts: Product[] = [
  {
    id: 'prd1',
    code: 'PRD-001',
    name: 'Centrifugal Pump CP-202',
    size: '10HP',
    description: 'High-performance centrifugal pump for heavy-duty industrial applications.',
    category: 'Machinery',
    unit: 'pcs',
    openingStock: 15,
    stock: 12,
    minStockAlert: 5,
    purchasePrice: 22000,
    sellingPrice: 28000,
    gstRate: 18,
    hsnCode: '8413',
    status: 'active',
  },
  {
    id: 'prd2',
    code: 'PRD-002',
    name: 'Carbon Steel Pipe 4" (6m)',
    size: '4 Inch',
    description: 'Seamless carbon steel pipe, 4-inch diameter, 6 meters length.',
    category: 'Hardware',
    unit: 'meter',
    openingStock: 200,
    stock: 150,
    minStockAlert: 50,
    purchasePrice: 3800,
    sellingPrice: 4500,
    gstRate: 18,
    hsnCode: '7304',
    status: 'active',
  },
  {
    id: 'prd3',
    code: 'PRD-003',
    name: 'Cast Iron Gate Valve 110mm',
    size: '110mm',
    description: 'Robust cast iron gate valve for water and gas flow control.',
    category: 'Fittings',
    unit: 'pcs',
    openingStock: 50,
    stock: 35,
    minStockAlert: 10,
    purchasePrice: 9500,
    sellingPrice: 12000,
    gstRate: 12,
    hsnCode: '8481',
    status: 'active',
  },
  {
    id: 'prd4',
    code: 'PRD-004',
    name: 'Welding Electrode 6013 (Pack)',
    size: 'Standard',
    description: 'General-purpose welding electrodes for mild steel fabrication.',
    category: 'Consumables',
    unit: 'box',
    openingStock: 100,
    stock: 85,
    minStockAlert: 20,
    purchasePrice: 650,
    sellingPrice: 850,
    gstRate: 18,
    hsnCode: '8311',
    status: 'active',
  },
  {
    id: 'prd5',
    code: 'PRD-005',
    name: 'Industrial Pressure Gauge',
    size: '0-500 Bar',
    description: 'Analog pressure gauge for monitoring industrial pipe systems.',
    category: 'Instrumentation',
    unit: 'pcs',
    openingStock: 30,
    stock: 22,
    minStockAlert: 8,
    purchasePrice: 1800,
    sellingPrice: 2400,
    gstRate: 18,
    hsnCode: '9026',
    status: 'active',
  },
];

export const dummyTransactions: Transaction[] = [
  {
    id: 't1',
    type: 'sale',
    serialNumber: 'SR-2024-001',
    companyId: 'c2',
    companyName: 'Bharat Heavy Electricals Ltd',
    billingAddress: 'BHEL House, Siri Fort, New Delhi-110049',
    placeOfSupply: 'Delhi',
    lineItems: [
      { id: 'li1', productId: 'prd1', description: 'Centrifugal Pump CP-202', quantity: 2, unit: 'pcs', unitPrice: 28000, gstRate: 18, lineTotal: 56000 },
      { id: 'li2', productId: 'prd3', description: 'Cast Iron Gate Valve 110mm', quantity: 5, unit: 'pcs', unitPrice: 12000, gstRate: 12, lineTotal: 60000 },
    ],
    subtotal: 116000,
    taxableAmount: 116000,
    cgstAmount: 5040,
    sgstAmount: 5040,
    totalGst: 10080,
    totalAmount: 126080,
    amountPaid: 126080,
    balanceDue: 0,
    date: '2024-03-15',
    dueDate: '2024-05-14',
    paymentStatus: 'paid',
    status: 'confirmed',
  },
  {
    id: 't2',
    type: 'sale',
    serialNumber: 'SR-2024-002',
    companyId: 'c4',
    companyName: 'MMRDA - Metro Line 3',
    billingAddress: 'Bandra-Kurla Complex, Bandra (E), Mumbai-400051',
    placeOfSupply: 'Maharashtra',
    lineItems: [
      { id: 'li3', productId: 'prd2', description: 'Carbon Steel Pipe 4" (6m)', quantity: 100, unit: 'meter', unitPrice: 4500, gstRate: 18, lineTotal: 450000 },
    ],
    subtotal: 450000,
    taxableAmount: 450000,
    cgstAmount: 40500,
    sgstAmount: 40500,
    totalGst: 81000,
    totalAmount: 531000,
    amountPaid: 0,
    balanceDue: 531000,
    date: '2024-03-20',
    dueDate: '2024-06-18',
    paymentStatus: 'pending',
    status: 'confirmed',
  },
  {
    id: 't3',
    type: 'purchase',
    serialNumber: 'SR-2024-003',
    supplierInvoiceNumber: 'PREC-987',
    companyId: 'c1',
    companyName: 'Precision Engineering Shoppe',
    billingAddress: 'G-12, Industrial Estate, Phase 3, Andheri West, Mumbai-400053',
    lineItems: [
      { id: 'li4', productId: 'prd1', description: 'Centrifugal Pump CP-202', quantity: 10, unit: 'pcs', unitPrice: 22000, gstRate: 18, lineTotal: 220000 },
    ],
    subtotal: 220000,
    taxableAmount: 220000,
    cgstAmount: 19800,
    sgstAmount: 19800,
    totalGst: 39600,
    totalAmount: 259600,
    amountPaid: 100000,
    balanceDue: 159600,
    date: '2024-02-10',
    dueDate: '2024-03-26',
    paymentStatus: 'partial',
    status: 'confirmed',
  },
  {
    id: 't4',
    type: 'purchase',
    serialNumber: 'SR-2024-004',
    supplierInvoiceNumber: 'SHIV-GST-44',
    companyId: 'c3',
    companyName: 'Shivam Steel Traders',
    lineItems: [
      { id: 'li5', productId: 'prd4', description: 'Welding Electrode 6013 (Pack)', quantity: 50, unit: 'box', unitPrice: 650, gstRate: 18, lineTotal: 32500 },
    ],
    subtotal: 32500,
    taxableAmount: 32500,
    totalGst: 5850,
    totalAmount: 38350,
    amountPaid: 38350,
    balanceDue: 0,
    date: '2024-03-05',
    dueDate: '2024-04-04',
    paymentStatus: 'paid',
    status: 'confirmed',
  },
];

export const dummyPayments: Payment[] = [
  {
    id: 'p1',
    paymentNumber: 'PAY-RCV-001',
    paymentType: 'received',
    linkedTransactionId: 't1',
    companyId: 'c2',
    companyName: 'Bharat Heavy Electricals Ltd',
    paymentDate: '2024-03-25',
    amount: 126080,
    paymentMode: 'bank_transfer',
    referenceNumber: 'NEFT-BHEL-7722',
    status: 'completed',
  },
  {
    id: 'p2',
    paymentNumber: 'PAY-SNT-001',
    paymentType: 'sent',
    linkedTransactionId: 't3',
    companyId: 'c1',
    companyName: 'Precision Engineering Shoppe',
    paymentDate: '2024-03-01',
    amount: 100000,
    paymentMode: 'bank_transfer',
    referenceNumber: 'UPI-PR-9921',
    status: 'completed',
  },
];

export const dummyExpenses: Expense[] = [
  {
    id: 'e1',
    expenseNumber: 'EXP-2024-001',
    expenseType: 'courier',
    expenseDate: '2024-03-22',
    courierName: 'Blue Dart',
    dispatcherName: 'Ramesh',
    trackingNumber: '77221199',
    courierAmount: 450,
    totalExpense: 450,
    notes: 'Urgent documents to BHEL',
    status: 'approved',
  },
  {
    id: 'e2',
    expenseNumber: 'EXP-2024-002',
    expenseType: 'travel',
    expenseDate: '2024-03-18',
    fromLocation: 'Office',
    toLocation: 'Bandra Metro Site',
    travelMode: 'Taxi',
    travelAmount: 850,
    totalExpense: 850,
    purposeOfTravel: 'Site Inspection',
    status: 'approved',
  },
];

export const dummyReturns: Return[] = [
  {
    id: 'r1',
    returnNumber: 'RTN-2024-001',
    type: 'sale',
    returnType: 'sales',
    originalTransactionId: 't1',
    originalSerialNumber: 'SR-2024-001',
    companyId: 'c2',
    companyName: 'Bharat Heavy Electricals Ltd',
    returnDate: '2024-03-28',
    returnReason: 'Wrong size valve delivered',
    refundType: 'credit_note',
    refundAmount: 12000,
    status: 'pending',
  },
];

export const dummyNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'payment_due',
    severity: 'warning',
    linkedModule: 'sales',
    referenceId: 't2',
    transactionId: 't2',
    companyId: 'c4',
    companyName: 'MMRDA - Metro Line 3',
    message: 'Payment due soon for Serial SR-2024-002 - ₹5,31,000',
    date: '2024-04-10',
    read: false,
    actionUrl: '/sales',
  },
  {
    id: 'n2',
    type: 'low_stock',
    severity: 'critical',
    linkedModule: 'inventory',
    referenceId: 'prd1',
    transactionId: 'prd1',
    companyId: 'system',
    message: 'Critical Stock Alert: Centrifugal Pump CP-202 is below threshold (Current: 12)',
    date: '2024-04-11',
    read: false,
    actionUrl: '/inventory',
  },
];

export const demoUsers: User[] = [
  {
    id: 'u1',
    username: 'admin',
    password: 'admin123',
    name: 'Admin User',
    role: 'admin',
    accessibleModules: ['/home', '/sales', '/purchases', '/returns', '/expenses', '/companies', '/customers', '/inventory', '/inventory-master', '/payments', '/notifications', '/settings'],
  },
  {
    id: 'u2',
    username: 'user',
    password: 'user123',
    name: 'Standard User',
    role: 'user',
    accessibleModules: ['/home', '/sales', '/returns', '/inventory', '/inventory-master', '/notifications'],
  },
];

export const dummyUser = demoUsers[0];
export const dummyCredentials = {
  username: demoUsers[0].username,
  password: demoUsers[0].password!,
};
